# Generated by Django 4.2.11 on 2024-05-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите имя бренда', max_length=144, verbose_name='Название бренда')),
                ('country', models.CharField(help_text='Страна, в которой основан бренд', max_length=144, verbose_name='Страна происхождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Укажите тип одежды, например, футболка, брюки, куртка и т.д.', max_length=255, verbose_name='Тип одежды')),
                ('name', models.CharField(help_text='Укажите название одежды', max_length=255, verbose_name='Название одежды')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену одежды', max_digits=10, verbose_name='Цена')),
                ('material', models.CharField(help_text='Укажите материал, из которого сделана одежда', max_length=255, verbose_name='Материал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('brand', models.ForeignKey(help_text='Выберите бренд для этой одежды', on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
        ),
    ]
