# Generated by Django 4.2.11 on 2024-05-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя персоны (максимум 50 символов).', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию персоны (максимум 50 символов).', max_length=50, verbose_name='Фамилия')),
                ('has_license', models.BooleanField(help_text='Укажите, имеет ли персона водительские права.', verbose_name='Наличие водительских прав')),
                ('license_category', models.CharField(blank=True, help_text='Введите категорию водительских прав, если есть (например, B, C, A). Опциональное поле.', max_length=2, verbose_name='Категория водительских прав')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Введите модель автомобиля (максимум 50 символов).', max_length=50, verbose_name='Модель')),
                ('brand', models.CharField(help_text='Введите марку автомобиля (максимум 50 символов).', max_length=50, verbose_name='Марка')),
                ('year', models.PositiveIntegerField(help_text='Введите год выпуска автомобиля.', verbose_name='Год выпуска')),
                ('registration_number', models.CharField(help_text='Введите уникальный регистрационный номер автомобиля (максимум 20 символов).', max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(help_text='Выберите владельца автомобиля.', on_delete=django.db.models.deletion.CASCADE, to='main.person', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
