# Generated by Django 5.0.4 on 2024-05-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Укажите ваше имя (максимум 50 символов).', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Укажите вашу фамилию (максимум 50 символов).', max_length=50, verbose_name='Фамилия')),
                ('has_license', models.BooleanField(default=False, help_text='Укажите, есть ли у вас водительские права.', verbose_name='Наличие водительских прав')),
                ('license_category', models.CharField(blank=True, help_text='Укажите категорию водительских прав (например, B, C, A). Оставьте пустым, если нет прав.', max_length=2, null=True, verbose_name='Категория прав')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Укажите модель автомобиля (максимум 50 символов).', max_length=50, verbose_name='Модель')),
                ('brand', models.CharField(help_text='Укажите марку автомобиля (максимум 50 символов).', max_length=50, verbose_name='Марка')),
                ('year', models.PositiveIntegerField(help_text='Укажите год выпуска автомобиля.', verbose_name='Год выпуска')),
                ('registration_number', models.CharField(help_text='Укажите уникальный регистрационный номер автомобиля.', max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('owner', models.ForeignKey(help_text='Укажите владельца автомобиля.', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.person', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
